In [1]:
import numpy as np

In [5]:
x = [0,1.1,3]

In [3]:
type(x)

list

In [6]:
type(x[1])

float

In [7]:
type(x)

list

In [8]:
y = np.array(x)

In [9]:
type(y)

numpy.ndarray

In [10]:
type(y[0])

numpy.float64

In [12]:
str.isdigit(x)

TypeError: descriptor 'isdigit' requires a 'str' object but received a 'list'

In [35]:
a =np.array([1,2,3])
type(a)


numpy.ndarray

In [19]:
scale = lambda x : str.isdigit(str(x))
p = scale(a)

In [20]:
p

False

In [21]:
a

array([1, 2, 3])

In [54]:
def is_number(a):
    boolean = True
    
    for i in a:
        # will be True also for 'NaN'
        try:
            number = float(i)
        except ValueError:
            boolean = False
    
    return boolean

In [42]:
a_l = [1,2,3]
b_l = [1,2,'NaN']
c_l = [1,2,3.3]
d_l = [1,2,'stuff']

a_a = np.array([1,2,3])
b_a = np.array([1,2,'NaN'])
c_a = np.array([1,2,3.3])
d_a = np.array([1,2,'stuff'])

In [59]:
is_number(a_a)

True

In [39]:
np.isnan(a)

array([False, False, False])

In [52]:
int(1)

1

In [60]:
len(a_a)

3

In [63]:
def len_test(series, split):
    length = len(series)
    feasibility = True
    
    if length > 9 and split < length:
        pass
    else:
        feasibility = False
    
    return feasibility
        

In [67]:
len_test(b,1)

True

In [66]:
b = np.array([1,2,3,4,5,6,7,8,9,9,8])

In [79]:
def split(series, split):
    #length = len(series)
    
    test = series[split:]
    train = series[:split]
    
    return test, train

In [69]:
x = np.arange(9.0)
np.split(x, 3)
#[array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.,  8.])]

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [86]:
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [73]:
x[4:]

array([4., 5., 6., 7., 8.])

In [74]:
x[:4]

array([0., 1., 2., 3.])

In [91]:
split(x, 4)

(array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.]))

In [92]:
train, test = split(x,4)

In [93]:
train

array([0., 1., 2., 3., 4.])

In [90]:
def split(series, split):
    length = len(series)
    val = length - split
    
    test = series[val:]
    train = series[:val]
    
    return train,test